apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: development
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: nginx
        resources:
          limits:
            cpu: 300m
            memory: 400Mi
        requests:
          cpu: 200m
          memory: 200Mi
      ports:
      - containerPort: 80
        name: http
        protocol: TCP
