apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: frontend
